const products=[
{id:1,emoji:"🎧",name:"Wireless Earbuds",price:1299,old:2999,discount:"56% OFF",rating:4.6,category:"Electronics",desc:"Clear sound, compact charging case and all-day battery life."},
{id:2,emoji:"⌚",name:"ColorFit Pro 5 Smartwatch",price:2499,old:4999,discount:"50% OFF",rating:4.5,category:"Electronics",desc:"A stylish smartwatch with health tracking, notifications and fitness modes."},
{id:3,emoji:"👟",name:"Nike Running Shoes Men's",price:4999,old:8995,discount:"44% OFF",rating:4.7,category:"Fashion",desc:"Lightweight everyday running shoes designed for comfort and performance."},
{id:4,emoji:"🍳",name:"Philips Air Fryer 4.1L",price:6499,old:10995,discount:"41% OFF",rating:4.4,category:"Appliances",desc:"Crispy meals with less oil, easy controls and a spacious cooking basket."},
{id:5,emoji:"🧴",name:"Luxury Perfume Set",price:599,old:1299,discount:"54% OFF",rating:4.3,category:"Beauty",desc:"A premium fragrance set suitable for everyday wear and gifting."},
{id:6,emoji:"💻",name:"Apple MacBook Air",price:89900,old:0,discount:"",rating:4.8,category:"Electronics",desc:"A slim, powerful laptop for work, study and creativity."},
{id:7,emoji:"📱",name:"Samsung Galaxy S24",price:74999,old:0,discount:"",rating:4.7,category:"Mobiles",desc:"Premium smartphone with a bright display, powerful processor and advanced camera."},
{id:8,emoji:"🎧",name:"Premium Wireless Headphones",price:29990,old:0,discount:"",rating:4.6,category:"Electronics",desc:"Immersive wireless audio with comfortable over-ear design."},
{id:9,emoji:"🎒",name:"The North Face Backpack",price:5499,old:0,discount:"",rating:4.5,category:"Fashion",desc:"Durable everyday backpack with practical storage for work and travel."},
{id:10,emoji:"👕",name:"Adidas Men's T-Shirt",price:1299,old:0,discount:"",rating:4.5,category:"Fashion",desc:"Comfortable casual t-shirt with a clean athletic look."}
];
let cart=JSON.parse(localStorage.getItem("shopmailCart")||"[]");
const money=n=>"₹"+n.toLocaleString("en-IN");
function stars(r){return "★★★★★ <span style='color:#6b7280'>("+r.toFixed(1)+")</span>"}
function card(p){return `<article class="product"><span class="badge">${p.discount||"TOP PICK"}</span><div class="pic" onclick="openProduct(${p.id})">${p.emoji}</div><h3 onclick="openProduct(${p.id})">${p.name}</h3><div class="stars">${stars(p.rating)}</div><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><button class="cart-btn" onclick="addToCart(${p.id})">🛒 Add to Cart</button></article>`}
function renderHome(){document.getElementById("dealProducts").innerHTML=products.slice(0,5).map(card).join("");document.getElementById("featuredProducts").innerHTML=products.slice(5).map(card).join("");updateCount()}
function save(){localStorage.setItem("shopmailCart",JSON.stringify(cart));updateCount()}
function updateCount(){document.getElementById("cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function addToCart(id,qty=1){let x=cart.find(i=>i.id===id);if(x)x.qty+=qty;else cart.push({id,qty});save();toast("Added to cart ✓")}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
function openProduct(id){let p=products.find(x=>x.id===id);document.getElementById("home").classList.add("hidden");document.getElementById("productPage").classList.remove("hidden");document.getElementById("cartPage").classList.add("hidden");document.getElementById("productPage").innerHTML=`<div class="product-detail"><div class="detail-pic">${p.emoji}</div><div class="detail"><button class="back" onclick="goHome()">← Back to store</button><p class="eyebrow">${p.category.toUpperCase()}</p><h1>${p.name}</h1><div class="stars">${stars(p.rating)}</div><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:""}</div><p>${p.desc}</p><ul><li>Fast delivery across India</li><li>Easy returns</li><li>Secure checkout</li></ul><div class="qty"><button onclick="changeQty(-1)">−</button><input id="detailQty" value="1" readonly><button onclick="changeQty(1)">+</button></div><button class="buy-btn" onclick="addFromDetail(${p.id})">Add to Cart</button><button class="buy-btn" onclick="addFromDetail(${p.id});openCart()">Buy Now</button></div></div>`;window.scrollTo(0,0)}
function changeQty(n){let q=document.getElementById("detailQty");q.value=Math.max(1,+q.value+n)}
function addFromDetail(id){addToCart(id,+document.getElementById("detailQty").value)}
function openCart(){document.getElementById("home").classList.add("hidden");document.getElementById("productPage").classList.add("hidden");let page=document.getElementById("cartPage");page.classList.remove("hidden");let items=cart.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty}));let total=items.reduce((a,x)=>a+x.price*x.qty,0);page.innerHTML=`<div class="cart-wrap"><button class="back" onclick="goHome()">← Continue Shopping</button><h1>Shopping Cart</h1>${items.length?items.map(x=>`<div class="cart-item"><div class="thumb">${x.emoji}</div><h3>${x.name}<br><small>${money(x.price)} × ${x.qty}</small></h3><b>${money(x.price*x.qty)}</b><button class="remove" onclick="removeFromCart(${x.id})">Remove</button></div>`).join(""):`<div class="cart-item"><h3>Your cart is empty.</h3></div>`}${items.length?`<div class="summary"><p>Subtotal</p><strong>${money(total)}</strong><br><button class="buy-btn" onclick="toast('Checkout is the next step ✓')">Proceed to Checkout</button></div>`:""}</div>`;window.scrollTo(0,0)}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);save();openCart()}
function goHome(){document.getElementById("home").classList.remove("hidden");document.getElementById("productPage").classList.add("hidden");document.getElementById("cartPage").classList.add("hidden");window.scrollTo(0,0)}
function searchProducts(){let q=document.getElementById("searchInput").value.toLowerCase().trim();if(!q){goHome();return}document.getElementById("home").classList.remove("hidden");document.getElementById("productPage").classList.add("hidden");document.getElementById("cartPage").classList.add("hidden");document.getElementById("dealProducts").innerHTML=products.filter(p=>(p.name+" "+p.category+" "+p.desc).toLowerCase().includes(q)).map(card).join("")||"<p>No products found.</p>";document.getElementById("featuredProducts").innerHTML=""}
document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")searchProducts()});
renderHome();